In [1]:
import torch

In [48]:
dataset_base_dir = '/shared/share_mala/implicitbayes/dataset_files/synthetic_data/binary_context_redo//N=2000,D=10000,D_eval=10000,binaryX=False,cnts=5.0,method=shareU_0702,one_X_per_col=False/'

In [49]:
train_data = torch.load(dataset_base_dir + '/train_data.pt')

In [50]:
eval_data = torch.load(dataset_base_dir + '/eval_data.pt')

In [45]:
generate_fn = lambda D,N,binary,ave_U,g: generate_data_beta_context_shareU(D=D,N=N,binaryX=binary,cnts=args.cnts,one_X_per_col=args.one_X_per_col,ave_U=ave_U,num_Us=0, uniform=False, generator=g)

In [57]:
assert train_data['click_rate'][0,0] != eval_data['click_rate'][0,0]

In [52]:
eval_data['Z']

tensor([[0.0786],
        [0.3721],
        [0.9007],
        ...,
        [0.9442],
        [0.4205],
        [0.3163]])

In [63]:
g = torch.Generator()
#g.initial_seed()
torch.rand(20, generator=g)

tensor([0.2673, 0.8725, 0.3353, 0.4030, 0.7871, 0.4576, 0.0719, 0.9715, 0.7147,
        0.4275, 0.0846, 0.4904, 0.1662, 0.1538, 0.3638, 0.5145, 0.7122, 0.8787,
        0.8431, 0.9879])

In [20]:
g = torch.Generator()
g.initial_seed()
torch.rand(20, generator=g)

tensor([0.2673, 0.8725, 0.3353, 0.4030, 0.7871, 0.4576, 0.0719, 0.9715, 0.7147,
        0.4275, 0.0846, 0.4904, 0.1662, 0.1538, 0.3638, 0.5145, 0.7122, 0.8787,
        0.8431, 0.9879])

In [21]:
g = torch.Generator()
g.initial_seed()
torch.rand(20, generator=g)

tensor([0.2673, 0.8725, 0.3353, 0.4030, 0.7871, 0.4576, 0.0719, 0.9715, 0.7147,
        0.4275, 0.0846, 0.4904, 0.1662, 0.1538, 0.3638, 0.5145, 0.7122, 0.8787,
        0.8431, 0.9879])